### ISSUE TITLE
ClearlyDefined collaboration?

### ISSUE THREAD

**Issue by jeffmcaffer** [jslicense/npm-license-corrections.json#8]
We have been driving a similar effort at https://clearlydefined.io. It would be great to find ways of collaborating. Some questions to see what might work?

* What are the use cases you are trying to address here? 
* Are the REST APIs described at https://api.clearlydefined.io/api-docs of any use in these scenarios?

**Comment by kemitchell** [comment]
This package is downstream of `npm` CLI.

**Comment by jeffmcaffer** [comment]
Right. I was wondering if the data here is only for use with `licensee` or are there other cases? Can licensee call REST APIs? 

If so, would you need changes to the ClearlyDefined API for it to be useful? 

If not, would it make sense to have ClearlyDefined publish an equivalent NPM any time the licenses for the top 1000 change? (or some such)

**Comment by kemitchell** [comment]
@jeffmcaffer I can't speak for the npm CLI team, but I suspect they won't be interested in calling out to third-party services. Many people use npm behind firewalls, connected to company-specific registries. The hand-coded heuristics in this package have proven largely good enough to offer reasonable corrections to mistyped `license` properties.

**Comment by jeffmcaffer** [comment]
Thanks for the detail @kemitchell 

I had interpreted "downstream of npm cli" to mean used *after* `npm` not *by* `npm`. So yeah, would not expect REST calls to be a good thing.

In that case would the second option (have ClearlyDefined generate the equivalent of this package proactively) be make sense? There are a few paths we could go here
1) Have something where we have a list of "packages of interest" and whenever one of those changes we regen and publish the npm with the full list
2) We have a "feed" of changes that you listen to and gen whatever packages you want

The second is something we've been wanting to do anyway. Obviously requires more infrastructure on your side but nothing that couldn't be done with a relatively simple Function or Lambda. 

My main motivation here is to coalesce on one set of curations that is useful in many places. Don't want to force a square peg into a round hole but we are quite willing to be inventive to make the data more useful in more places.

**Comment by kemitchell** [comment]
@jeffmcaffer My apologies. I had this package mixed up with another, which I've maintained much longer.

This package is not among npm CLI's dependencies, though it may end up so, if npm CLI implements its own license-audit command. Again, I can't speak for the CLI team. But I wouldn't be surprised to see those changes.

The same applies to https://github.com/jslicense/correct-license-metadata.js, which the `licensee` uses together with this package.

I am not against sharing data, but this package does aim to be a static, installable data package that does _not_ require network access. FWIW, I think the data format here is simple enough that it will be easy for others to adapt the data to their own systems.

**Comment by jeffmcaffer** [comment]
+1 on static content etc. I am more after capturing the curation/correction work in one place. For example, have folks do the corrections at ClearlyDefined and then machine generate this package in the same format as it is currently. 

As a concrete example, imagine the "build" for this package was to do a `curl` get the CSV content and then just published that to npm. For example, this command line will get the full definitions for the two listed packages. Imagine we added a `accepts` header or some such to give back the CSV rather than the JSON as it does by default.

`curl -H "Content-Type: application/json" -d [\"npm/npmjs/-/async/2.6.0\",\"npm/npmjs/-/lodash/0.85.2\"] https://api.clearlydefined.io/definitions`

At that point it becomes a question of when to run the build. Could run daily and only publish the package if there are changes. Could be on demand. Could be triggered by new definition values. Whatever makes it easy for the curations to get consumed.
